export const POPULAR_CA_SCHOOLS = [
  "Abram Friedman Occupational School",
  "Academy of the Canyons",
  "Adolfo Camarillo High School",
  "Adrian Wilcox High School",
  "Agis High School",
  "Agoura High School",
  "Alameda High School",
  "Alhambra High School",
  "Aliso Niguel High School",
  "Alta Loma High School",
  "Amador Valley High School",
  "American High School",
  "Anaheim High School",
  "Antelope High School",
  "Antelope Valley High School",
  "Arcadia High School",
  "Arroyo High School",
  "Arroyo Grande High School",
  "Artesia High School",
  "Ayala High School",
  "Baldwin Park High School",
  "Banning High School",
  "Barstow High School",
  "Bear Creek High School",
  "Bell High School",
  "Bellarmine College Preparatory",
  "Belmont High School",
  "Berkeley High School",
  "Beverly Hills High School",
  "Bishop Montgomery High School",
  "Bonita High School",
  "Brea Olinda High School",
  "Bullard High School",
  "Burbank High School",
  "Burlingame High School",
  "California High School",
  "Calvary Chapel High School",
  "Camarillo High School",
  "Campolindo High School",
  "Canyon High School",
  "Carlmont High School",
  "Carlsbad High School",
  "Carmel High School",
  "Castlemont High School",
  "Castro Valley High School",
  "Centennial High School",
  "Century High School",
  "Cerritos High School",
  "Chaminade College Preparatory",
  "Charter Oak High School",
  "Chatsworth High School",
  "Chino High School",
  "Chino Hills High School",
  "Chula Vista High School",
  "Citrus Hill High School",
  "Citrus Valley High School",
  "Claremont High School",
  "Clovis High School",
  "Clovis East High School",
  "Clovis North High School",
  "Clovis West High School",
  "Colton High School",
  "Corona High School",
  "Corona del Mar High School",
  "Costa Mesa High School",
  "Crespi Carmelite High School",
  "Cypress High School",
  "Dana Hills High School",
  "Davis Senior High School",
  "De La Salle High School",
  "Del Mar High School",
  "Del Norte High School",
  "Diamond Bar High School",
  "Dominguez High School",
  "Dos Pueblos High School",
  "Downey High School",
  "Dublin High School",
  "Eagle Rock High School",
  "Eastlake High School",
  "Edison High School",
  "El Camino High School",
  "El Camino Real High School",
  "El Dorado High School",
  "El Modena High School",
  "El Rancho High School",
  "El Segundo High School",
  "El Toro High School",
  "Elk Grove High School",
  "Esperanza High School",
  "Etivanda High School",
  "Eureka High School",
  "Fairfield High School",
  "Fallbrook High School",
  "Folsom High School",
  "Fontana High School",
  "Foothill High School",
  "Fountain Valley High School",
  "Franklin High School",
  "Fremont High School",
  "Fullerton High School",
  "Gahr High School",
  "Galileo Academy of Science and Technology",
  "Garden Grove High School",
  "Gardena High School",
  "Glendale High School",
  "Glendora High School",
  "Granada High School",
  "Granada Hills Charter High School",
  "Gunn High School",
  "Hacienda Heights High School",
  "Hanford High School",
  "Hart High School",
  "Hayward High School",
  "Helix High School",
  "Heritage High School",
  "Highland High School",
  "Homestead High School",
  "Huntington Beach High School",
  "Inderkum High School",
  "Irvine High School",
  "James Logan High School",
  "John Burroughs High School",
  "John F. Kennedy High School",
  "Jordan High School",
  "Jurupa Valley High School",
  "Katella High School",
  "Kennedy High School",
  "Laguna Beach High School",
  "Laguna Hills High School",
  "Lakeside High School",
  "Lakewood High School",
  "Lancaster High School",
  "La Quinta High School",
  "La Serna High School",
  "Las Lomas High School",
  "Leland High School",
  "Lincoln High School",
  "Livermore High School",
  "Lodi High School",
  "Long Beach Polytechnic High School",
  "Los Alamitos High School",
  "Los Altos High School",
  "Los Amigos High School",
  "Los Gatos High School",
  "Lowell High School",
  "Loyola High School",
  "Lynbrook High School",
  "Madera High School",
  "Marina High School",
  "Martin Luther King High School",
  "Mater Dei High School",
  "Mayfair High School",
  "Menlo-Atherton High School",
  "Millikan High School",
  "Milpitas High School",
  "Mira Costa High School",
  "Mira Loma High School",
  "Mission Viejo High School",
  "Modesto High School",
  "Monrovia High School",
  "Monte Vista High School",
  "Monterey Trail High School",
  "Moorpark High School",
  "Moreno Valley High School",
  "Mountain View High School",
  "Mt. Carmel High School",
  "Murrieta Mesa High School",
  "Murrieta Valley High School",
  "Napa High School",
  "Newbury Park High School",
  "Newport Harbor High School",
  "North High School",
  "Northgate High School",
  "Northview High School",
  "Norwalk High School",
  "Notre Dame High School",
  "Oak Ridge High School",
  "Oaks Christian School",
  "Ocean View High School",
  "Oceanside High School",
  "Ontario High School",
  "Orange Glen High School",
  "Orange High School",
  "Orange Lutheran High School",
  "Oxnard High School",
  "Pacific High School",
  "Palisades Charter High School",
  "Palm Desert High School",
  "Palm Springs High School",
  "Palo Alto High School",
  "Paloma Valley High School",
  "Palos Verdes High School",
  "Paramount High School",
  "Pasadena High School",
  "Paso Robles High School",
  "Patterson High School",
  "Peninsula High School",
  "Piedmont High School",
  "Pioneer High School",
  "Pittsburg High School",
  "Placentia High School",
  "Pleasant Valley High School",
  "Pomona High School",
  "Poway High School",
  "Quartz Hill High School",
  "Rancho Bernardo High School",
  "Rancho Cucamonga High School",
  "Redlands High School",
  "Redlands East Valley High School",
  "Redondo Union High School",
  "Redwood High School",
  "Ridgeview High School",
  "Rim of the World High School",
  "Rio Americano High School",
  "Rio Mesa High School",
  "Riverside Polytechnic High School",
  "Rocklin High School",
  "Rodriguez High School",
  "Rosemead High School",
  "Roseville High School",
  "Rowland High School",
  "Sacramento High School",
  "San Clemente High School",
  "San Diego High School",
  "San Gabriel High School",
  "San Jacinto High School",
  "San Jose High School",
  "San Leandro High School",
  "San Luis Obispo High School",
  "San Marcos High School",
  "San Marin High School",
  "San Mateo High School",
  "San Pasqual High School",
  "San Ramon Valley High School",
  "Santa Ana High School",
  "Santa Barbara High School",
  "Santa Clara High School",
  "Santa Cruz High School",
  "Santa Margarita Catholic High School",
  "Santa Monica High School",
  "Santa Rosa High School",
  "Santa Teresa High School",
  "Santana High School",
  "Santiago High School",
  "Saratoga High School",
  "Savanna High School",
  "Scripps Ranch High School",
  "Segerstrom High School",
  "Serra High School",
  "Shadow Hills High School",
  "Simi Valley High School",
  "Skyline High School",
  "Sonoma Valley High School",
  "South High School",
  "South Gate High School",
  "South Hills High School",
  "South Pasadena High School",
  "Stockton High School",
  "St. Francis High School",
  "St. Ignatius College Preparatory",
  "St. John Bosco High School",
  "St. Mary's High School",
  "Sunny Hills High School",
  "Sutter High School",
  "Tehachapi High School",
  "Temecula Valley High School",
  "Temple City High School",
  "Thousand Oaks High School",
  "Torrance High School",
  "Torrey Pines High School",
  "Tracy High School",
  "Troy High School",
  "Turlock High School",
  "Tustin High School",
  "University High School",
  "Upland High School",
  "Vacaville High School",
  "Valencia High School",
  "Vallejo High School",
  "Valley View High School",
  "Ventura High School",
  "Victor Valley High School",
  "Villa Park High School",
  "Vista High School",
  "Vista del Lago High School",
  "Vista Murrieta High School",
  "Walnut High School",
  "Warren High School",
  "West High School",
  "West Covina High School",
  "West Ranch High School",
  "Westlake High School",
  "Westminster High School",
  "Westview High School",
  "Whitney High School",
  "Whittier High School",
  "Wilson High School",
  "Woodbridge High School",
  "Woodcreek High School",
  "Woodland High School",
  "Yorba Linda High School",
  "Yucaipa High School"
];
