export const POPULAR_CA_SCHOOLS = [
  "Abram Friedman Occupational School (Los Angeles)",
  "Academy of the Canyons (Santa Clarita)",
  "Adolfo Camarillo High School (Camarillo)",
  "Adrian Wilcox High School (Santa Clara)",
  "Agis High School (Lafayette)",
  "Agoura High School (Agoura Hills)",
  "Alameda High School (Alameda)",
  "Alhambra High School (Alhambra)",
  "Aliso Niguel High School (Aliso Viejo)",
  "Alta Loma High School (Alta Loma)",
  "Amador Valley High School (Pleasanton)",
  "American High School (Fremont)",
  "Anaheim High School (Anaheim)",
  "Antelope High School (Antelope)",
  "Antelope Valley High School (Lancaster)",
  "Arcadia High School (Arcadia)",
  "Arroyo High School (El Monte)",
  "Arroyo Grande High School (Arroyo Grande)",
  "Artesia High School (Lakewood)",
  "Ayala High School (Chino Hills)",
  "Baldwin Park High School (Baldwin Park)",
  "Banning High School (Banning)",
  "Barstow High School (Barstow)",
  "Bear Creek High School (Stockton)",
  "Bell High School (Bell)",
  "Bellarmine College Preparatory (San Jose)",
  "Belmont High School (Los Angeles)",
  "Berkeley High School (Berkeley)",
  "Beverly Hills High School (Beverly Hills)",
  "Bishop Montgomery High School (Torrance)",
  "Bonita High School (La Verne)",
  "Brea Olinda High School (Brea)",
  "Bullard High School (Fresno)",
  "Burbank High School (Burbank)",
  "Burlingame High School (Burlingame)",
  "California High School (San Ramon)",
  "Calvary Chapel High School (Santa Ana)",
  "Camarillo High School (Camarillo)",
  "Campolindo High School (Moraga)",
  "Canyon High School (Anaheim)",
  "Carlmont High School (Belmont)",
  "Carlsbad High School (Carlsbad)",
  "Carmel High School (Carmel)",
  "Castlemont High School (Oakland)",
  "Castro Valley High School (Castro Valley)",
  "Centennial High School (Corona)",
  "Century High School (Santa Ana)",
  "Cerritos High School (Cerritos)",
  "Chaminade College Preparatory (West Hills)",
  "Charter Oak High School (Covina)",
  "Chatsworth High School (Chatsworth)",
  "Chino High School (Chino)",
  "Chino Hills High School (Chino Hills)",
  "Chula Vista High School (Chula Vista)",
  "Citrus Hill High School (Perris)",
  "Citrus Valley High School (Redlands)",
  "Claremont High School (Claremont)",
  "Clovis High School (Clovis)",
  "Clovis East High School (Clovis)",
  "Clovis North High School (Clovis)",
  "Clovis West High School (Clovis)",
  "Colton High School (Colton)",
  "Corona High School (Corona)",
  "Corona del Mar High School (Newport Beach)",
  "Costa Mesa High School (Costa Mesa)",
  "Crespi Carmelite High School (Encino)",
  "Cypress High School (Cypress)",
  "Dana Hills High School (Dana Point)",
  "Davis Senior High School (Davis)",
  "De La Salle High School (Concord)",
  "Del Mar High School (San Jose)",
  "Del Norte High School (San Diego)",
  "Diamond Bar High School (Diamond Bar)",
  "Dominguez High School (Compton)",
  "Dos Pueblos High School (Goleta)",
  "Downey High School (Downey)",
  "Dublin High School (Dublin)",
  "Eagle Rock High School (Los Angeles)",
  "Eastlake High School (Chula Vista)",
  "Edison High School (Huntington Beach)",
  "El Camino High School (Oceanside)",
  "El Camino Real High School (Woodland Hills)",
  "El Dorado High School (Placentia)",
  "El Modena High School (Orange)",
  "El Rancho High School (Pico Rivera)",
  "El Segundo High School (El Segundo)",
  "El Toro High School (Lake Forest)",
  "Elk Grove High School (Elk Grove)",
  "Esperanza High School (Anaheim)",
  "Etiwanda High School (Rancho Cucamonga)",
  "Eureka High School (Eureka)",
  "Fairfield High School (Fairfield)",
  "Fallbrook High School (Fallbrook)",
  "Folsom High School (Folsom)",
  "Fontana High School (Fontana)",
  "Foothill High School (Pleasanton)",
  "Fountain Valley High School (Fountain Valley)",
  "Franklin High School (Elk Grove)",
  "Fremont High School (Sunnyvale)",
  "Fullerton High School (Fullerton)",
  "Gahr High School (Cerritos)",
  "Galileo Academy of Science and Technology (San Francisco)",
  "Garden Grove High School (Garden Grove)",
  "Gardena High School (Gardena)",
  "Glendale High School (Glendale)",
  "Glendora High School (Glendora)",
  "Granada High School (Livermore)",
  "Granada Hills Charter High School (Granada Hills)",
  "Gunn High School (Palo Alto)",
  "Hacienda Heights High School (Hacienda Heights)",
  "Hanford High School (Hanford)",
  "Hart High School (Santa Clarita)",
  "Hayward High School (Hayward)",
  "Helix High School (La Mesa)",
  "Heritage High School (Menifee)",
  "Highland High School (Palmdale)",
  "Homestead High School (Sunnyvale)",
  "Huntington Beach High School (Huntington Beach)",
  "Inderkum High School (Sacramento)",
  "Irvine High School (Irvine)",
  "James Logan High School (Union City)",
  "John Burroughs High School (Burbank)",
  "John F. Kennedy High School (Fremont)",
  "Jordan High School (Long Beach)",
  "Jurupa Valley High School (Jurupa Valley)",
  "Katella High School (Anaheim)",
  "Kennedy High School (La Palma)",
  "Laguna Beach High School (Laguna Beach)",
  "Laguna Hills High School (Laguna Hills)",
  "Lakeside High School (Lake Elsinore)",
  "Lakewood High School (Lakewood)",
  "Lancaster High School (Lancaster)",
  "La Quinta High School (La Quinta)",
  "La Serna High School (Whittier)",
  "Las Lomas High School (Walnut Creek)",
  "Leland High School (San Jose)",
  "Lincoln High School (San Jose)",
  "Livermore High School (Livermore)",
  "Lodi High School (Lodi)",
  "Long Beach Polytechnic High School (Long Beach)",
  "Los Alamitos High School (Los Alamitos)",
  "Los Altos High School (Los Altos)",
  "Los Amigos High School (Fountain Valley)",
  "Los Gatos High School (Los Gatos)",
  "Lowell High School (San Francisco)",
  "Loyola High School (Los Angeles)",
  "Lynbrook High School (San Jose)",
  "Madera High School (Madera)",
  "Marina High School (Huntington Beach)",
  "Martin Luther King High School (Riverside)",
  "Mater Dei High School (Santa Ana)",
  "Mayfair High School (Lakewood)",
  "Menlo-Atherton High School (Atherton)",
  "Millikan High School (Long Beach)",
  "Milpitas High School (Milpitas)",
  "Mira Costa High School (Manhattan Beach)",
  "Mira Loma High School (Sacramento)",
  "Mission Viejo High School (Mission Viejo)",
  "Modesto High School (Modesto)",
  "Monrovia High School (Monrovia)",
  "Monte Vista High School (Danville)",
  "Monterey Trail High School (Elk Grove)",
  "Moorpark High School (Moorpark)",
  "Moreno Valley High School (Moreno Valley)",
  "Mountain View High School (Mountain View)",
  "Mt. Carmel High School (San Diego)",
  "Murrieta Mesa High School (Murrieta)",
  "Murrieta Valley High School (Murrieta)",
  "Napa High School (Napa)",
  "Newbury Park High School (Newbury Park)",
  "Newport Harbor High School (Newport Beach)",
  "North High School (Torrance)",
  "Northgate High School (Walnut Creek)",
  "Northview High School (Covina)",
  "Norwalk High School (Norwalk)",
  "Notre Dame High School (Sherman Oaks)",
  "Oak Ridge High School (El Dorado Hills)",
  "Oaks Christian School (Westlake Village)",
  "Ocean View High School (Huntington Beach)",
  "Oceanside High School (Oceanside)",
  "Ontario High School (Ontario)",
  "Orange Glen High School (Escondido)",
  "Orange High School (Orange)",
  "Orange Lutheran High School (Orange)",
  "Oxnard High School (Oxnard)",
  "Pacific High School (San Bernardino)",
  "Palisades Charter High School (Pacific Palisades)",
  "Palm Desert High School (Palm Desert)",
  "Palm Springs High School (Palm Springs)",
  "Palo Alto High School (Palo Alto)",
  "Paloma Valley High School (Menifee)",
  "Palos Verdes High School (Palos Verdes Estates)",
  "Paramount High School (Paramount)",
  "Pasadena High School (Pasadena)",
  "Paso Robles High School (Paso Robles)",
  "Patterson High School (Patterson)",
  "Peninsula High School (Rolling Hills Estates)",
  "Piedmont High School (Piedmont)",
  "Pioneer High School (San Jose)",
  "Pittsburg High School (Pittsburg)",
  "Placentia High School (Placentia)",
  "Pleasant Valley High School (Chico)",
  "Pomona High School (Pomona)",
  "Poway High School (Poway)",
  "Quartz Hill High School (Quartz Hill)",
  "Rancho Bernardo High School (San Diego)",
  "Rancho Cucamonga High School (Rancho Cucamonga)",
  "Redlands High School (Redlands)",
  "Redlands East Valley High School (Redlands)",
  "Redondo Union High School (Redondo Beach)",
  "Redwood High School (Larkspur)",
  "Ridgeview High School (Bakersfield)",
  "Rim of the World High School (Lake Arrowhead)",
  "Rio Americano High School (Sacramento)",
  "Rio Mesa High School (Oxnard)",
  "Riverside Polytechnic High School (Riverside)",
  "Rocklin High School (Rocklin)",
  "Rodriguez High School (Fairfield)",
  "Rosemead High School (Rosemead)",
  "Roseville High School (Roseville)",
  "Rowland High School (Rowland Heights)",
  "Sacramento High School (Sacramento)",
  "San Clemente High School (San Clemente)",
  "San Diego High School (San Diego)",
  "San Gabriel High School (San Gabriel)",
  "San Jacinto High School (San Jacinto)",
  "San Jose High School (San Jose)",
  "San Leandro High School (San Leandro)",
  "San Luis Obispo High School (San Luis Obispo)",
  "San Marcos High School (San Marcos)",
  "San Marin High School (Novato)",
  "San Mateo High School (San Mateo)",
  "San Pasqual High School (Escondido)",
  "San Ramon Valley High School (Danville)",
  "Santa Ana High School (Santa Ana)",
  "Santa Barbara High School (Santa Barbara)",
  "Santa Clara High School (Santa Clara)",
  "Santa Cruz High School (Santa Cruz)",
  "Santa Margarita Catholic High School (Rancho Santa Margarita)",
  "Santa Monica High School (Santa Monica)",
  "Santa Rosa High School (Santa Rosa)",
  "Santa Teresa High School (San Jose)",
  "Santana High School (Santee)",
  "Santiago High School (Corona)",
  "Saratoga High School (Saratoga)",
  "Savanna High School (Anaheim)",
  "Scripps Ranch High School (San Diego)",
  "Segerstrom High School (Santa Ana)",
  "Serra High School (San Diego)",
  "Shadow Hills High School (Indio)",
  "Simi Valley High School (Simi Valley)",
  "Skyline High School (Oakland)",
  "Sonoma Valley High School (Sonoma)",
  "South High School (Torrance)",
  "South Gate High School (South Gate)",
  "South Hills High School (West Covina)",
  "South Pasadena High School (South Pasadena)",
  "Stockton High School (Stockton)",
  "St. Francis High School (Mountain View)",
  "St. Ignatius College Preparatory (San Francisco)",
  "St. John Bosco High School (Bellflower)",
  "St. Mary's High School (Stockton)",
  "Sunny Hills High School (Fullerton)",
  "Sutter High School (Sutter)",
  "Tehachapi High School (Tehachapi)",
  "Temecula Valley High School (Temecula)",
  "Temple City High School (Temple City)",
  "Thousand Oaks High School (Thousand Oaks)",
  "Torrance High School (Torrance)",
  "Torrey Pines High School (San Diego)",
  "Tracy High School (Tracy)",
  "Troy High School (Fullerton)",
  "Turlock High School (Turlock)",
  "Tustin High School (Tustin)",
  "University High School (Irvine)",
  "Upland High School (Upland)",
  "Vacaville High School (Vacaville)",
  "Valencia High School (Valencia)",
  "Vallejo High School (Vallejo)",
  "Valley View High School (Moreno Valley)",
  "Ventura High School (Ventura)",
  "Victor Valley High School (Victorville)",
  "Villa Park High School (Villa Park)",
  "Vista High School (Vista)",
  "Vista del Lago High School (Moreno Valley)",
  "Vista Murrieta High School (Murrieta)",
  "Walnut High School (Walnut)",
  "Warren High School (Downey)",
  "West High School (Torrance)",
  "West Covina High School (West Covina)",
  "West Ranch High School (Stevenson Ranch)",
  "Westlake High School (Westlake Village)",
  "Westminster High School (Westminster)",
  "Westview High School (San Diego)",
  "Whitney High School (Cerritos)",
  "Whittier High School (Whittier)",
  "Wilson High School (Long Beach)",
  "Woodbridge High School (Irvine)",
  "Woodcreek High School (Roseville)",
  "Woodland High School (Woodland)",
  "Yorba Linda High School (Yorba Linda)",
  "Yucaipa High School (Yucaipa)"
];
